### PR TITLE
Modified setup command to also installed and configure Fluo.  Changed…

### PR DESCRIPTION
**Pull request by mikewalch**
… name of

deploy command to redeploy.  Deleted Fluo dashboard config as it now resides
in Fluo repo.  Setup command now gets Grafana dashboard config from Fluo tarball.

### CODE REVIEW

**Comment by keith-turner** [comment]
I tried running this change and fluo-io/fluo#572 with the webindex example.  I never saw any data for notifications queued.  Also looking at the output I was thinking maybe  the num of reads and writes should just be meters, measing how much each observer read and wrote and each second.

**Comment by mikewalch** [comment]
I am not sure why are not seeing notifications queued.  Can you follow the instructions below to make sure the metrics are getting to InfluxDB?

```bash
# Run InfluxDB CLI
./fluo-dev/install/influxdb-0.9.4.2/bin/influx
# In CLI, specify fluo_metrics db
> use fluo_metrics
# You should see "worker_notifications_queued" if you show all measurements
> show measurements
# You should see data if you query the measurement
> select * from worker_notifications_queued limit 3
name: worker_notifications_queued
---------------------------------
time                    app             host            value
2015-11-19T19:43:40Z    phrasecount     worker-0        88
2015-11-19T19:43:50Z    phrasecount     worker-0        2056
2015-11-19T19:44:00Z    phrasecount     worker-0        897
```

**Comment by mikewalch** [comment]
I agree that entries reads and writes should be meters rather than histograms.  I will update my Fluo PR.

**Comment by mikewalch** [comment]
In f1b88405078e, Modifed fluo-dev to pull Grafana dashboard config from `contrib/grafana` in Fluo distiribution.

**Comment by keith-turner** [comment]
+1

**Pull request merged**
